export const REQUEST_REGISTER_USER = "REQUEST_REGISTER_USER";
export const SUCCESS_REGISTER_USER = "SUCCESS_REGISTER_USER";
export const FAIL_REGISTER_USER = "FAIL_REGISTER_USER";
export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const SUCCESS_LOGIN_USER = "SUCCESS_LOGIN_USER";
export const FAIL_LOGIN_USER = "FAIL_LOGIN_USER";
export const LOGOUT_USER = "FAIL_LOGIN_USER";